### ISSUE TITLE
Problems with proxy and {:error, :closed}

### ISSUE THREAD

**Issue by atanych** [edgurgel/httpoison#308] opened 2018-02-07 14:42 UTC
Hi Guys,

I caught weird behavior when I worked behind proxy.

Server 1 (behind proxy):
OS: Redhat. 
`Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]`

```
options = [proxy: "http://xxx", proxy_auth: {"login", "pwd"}, ssl: [versions: [:'tlsv1.2']]]
:hackney.get("https://google.com", [], [], options)
```
![image](https://user-images.githubusercontent.com/10116909/35922016-71279900-0c2d-11e8-8278-9ae7ee01b52e.png)

```
url = "https://media-direct.cdn.viber.com/download_photo?dlid=Gsag08bVZ_qFBt5G_ssCKUKFN9MJsAodr-kKgBVxln9MbHaKkeJe5WHjkqILcgzfeell1-pwccBnMH3aFJwtu4F0glyNO-53pUJ8vSWbUnNxW9qVy-xY1_HO7g7Dpl5bcUvbaA&fltp=jpg&imsz=0000"
:hackney.get(url, [], [], options)
```
![image](https://user-images.githubusercontent.com/10116909/35922054-8ca429b4-0c2d-11e8-856a-d2386dde4325.png)

When I fetch image behind proxy, I receive {:error, :closed}

Server 2 (without proxy):
OS Centos.
`Erlang/OTP 20 [erts-9.1.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]`

Make the same things and receive correct result.
![image](https://user-images.githubusercontent.com/10116909/35922129-ce145608-0c2d-11e8-8383-e9acf87012d1.png)

I made the same things with HTTPoison. The similar response.

Could you help me to find solution or workaround for this issue?

Thanks!

**Comment by atanych** [comment] 2018-02-07 21:29
I figured out issue.

Was two problems:
- old elixir and erlang packages
- proxy is not used when follow_redirect is true

**Comment by edgurgel** [comment] 2021-10-01 23:03
Probably a duplicate of #112

**Closed by edgurgel** 2021-10-01 23:03 UTC
