### ISSUE TITLE
error if request response code 301

### ISSUE THREAD

**Issue by mvalitov** [edgurgel/httpoison#309] opened 2018-02-16 08:05 UTC
`HTTPoison.request` return error if response code 301
```
params = [ssl: [verify: :verify_none], follow_redirect: true, max_redirect: 7, hackney: [pool: false, insecure: true], proxy: {:socks5, '127.0.0.1', 8877}]
HTTPoison.request(:get, String.to_charlist("http://TreesDallas.com"), "", [], params)
{:error,
 %HTTPoison.Error{
   id: nil,
   reason: {:options,
    {:socket_options,
     [
       socks5_transport: :hackney_tcp,
       socks5_resolve: :undefined,
       socks5_pass: :undefined,
       socks5_user: :undefined,
       socks5_port: 8877,
       socks5_host: '127.0.0.1',
       insecure: true,
       ssl_options: [verify: :verify_none],
       packet_size: 0,
       packet: 0,
       header: 0,
       active: false,
       mode: :binary
     ]}}
 }}
```
without proxy
```
HTTPoison.request(:get, String.to_charlist("http://TreesDallas.com"), "", [], [follow_redirect: true])
{:ok,
 %HTTPoison.Response{
   body: "<!DOCTYPE html>\r\n<html lang=\"en-US\"...
<> ...,
   headers: [
     {"Server", "nginx"},
     {"Date", "Fri, 16 Feb 2018 07:32:01 GMT"},
     {"Content-Type", "text/html; charset=UTF-8"},
     {"Transfer-Encoding", "chunked"},
     {"Connection", "keep-alive"},
     {"Age", "1228"}
   ],
   request_url: "http://TreesDallas.com",
   status_code: 200
 }}
```

if follow_redirect: false
```
params = [ssl: [verify: :verify_none], follow_redirect: false, hackney: [pool: false, insecure: true], proxy: {:socks5, '127.0.0.1', 8877}] 
HTTPoison.request(:get, String.to_charlist("http://TreesDallas.com"), "", [], params)                                                      
{:ok,
 %HTTPoison.Response{
   body: "<html>\r\n<head><title>301 Moved Permanently</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>301 Moved Permanently</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n",
   headers: [
     {"Server", "nginx"},
     {"Date", "Fri, 16 Feb 2018 07:54:03 GMT"},
     {"Content-Type", "text/html"},
     {"Content-Length", "178"},
     {"Connection", "keep-alive"},
     {"Location", "https://treesdallas.com/"}
   ],
   request_url: "http://TreesDallas.com",
   status_code: 301
 }}
```
version
`{:httpoison, "~> 1.0"}`

**Comment by edgurgel** [comment] 2018-02-18 20:56
It seems to be related to https://github.com/edgurgel/httpoison/issues/308

**Comment by edgurgel** [comment] 2021-10-01 23:03
Probably a duplicate of https://github.com/edgurgel/httpoison/issues/112

**Closed by edgurgel** 2021-10-01 23:03 UTC
