### ISSUE TITLE
No AsyncEnd message is received on a 204 response missing content-length or transfer-encoding headers

### ISSUE THREAD

**Issue by jordan0day** [edgurgel/httpoison#33] opened 2015-01-07 21:19 UTC
I imagine this is basically the same issue as #10, but I ran into this today on the async side of things -- making an async request against a rails api that's running on phusion passenger, I get a 204 status and headers correctly, but I never get an %HTTPotion.AsyncEnd message -- I'm thinking this is because the server isn't supplying a content-length="0" header, nor a transfer-encoding header, so perhaps hackney is never sending the "done" message to HTTPoison? 

My erlang skills are pretty weak, so I'm not *sure* this is an issue in Hackney and not HTTPoison, but it seems likely. I tried writing a test for this in HTTPoison's test suite, but, as you mention in your comment from August 21, HTTParrot (via cowboy) always returns a content-length header, in which case the AsyncEnd message *is* being received.

For now I'll just not wait for an AsyncEnd message if the status is 204 or 304, but I wonder if HTTPoison should just go ahead and generate an AsyncEnd message if there's no content-length or transfer-encoding headers?

**Comment by edgurgel** [comment] 2015-01-07 21:32
Thanks for reporting, @jordan0day. I will take a look later today and give you some feedback. 

I suspect it's an issue on hackney, but I can't confirm without writing some tests on hackney.

**Comment by edgurgel** [comment] 2015-01-26 08:53
Just released [0.6.0 version](https://github.com/edgurgel/httpoison/releases/tag/0.6.0) that requires hackney ~> 1.0 and it will (from today) get a version higher than 1.0.6 which fixed this behaviour. Thanks to @lexmag for fixing this on hackney. 

I tested on my machine. If you find the same behaviour after using hackney 1.0.6 please reopen the issue.

**Comment by lexmag** [comment] 2015-01-26 12:33
@edgurgel my pleasure to help.

**Comment by jordan0day** [comment] 2015-01-26 14:29
:trophy: Thanks @edgurgel and @lexmag!

**Comment by DavsX** [comment] 2015-07-19 13:38
Using HTTPoison 0.7.0 and hackney 1.1.0 I don't get AsyncEnd message ever. The server does not send Content-length header and the only way to detect the end of a download is that at the end I got an AsyncChunk with an empty string. Is it intended?

**Comment by edgurgel** [comment] 2015-07-19 20:25
It's not intended. I will reopen the issue and investigate. Thanks for reporting.

**Comment by DavsX** [comment] 2015-07-19 21:00
The problematic link is the ElixirSips XML feed (elixirsips.com). I'm afraid you have to be subscribed to access that link (required basic_auth), so I cannot provide it for you.

**Comment by jordan0day** [comment] 2015-07-20 16:49
I have an ElixirSips subscription, and can replicate DavsX issue -- seeing the Async response streamed, and when it comes to the end, you get a final AsyncChunk with an empty string, and no AsyncEnd message sent.

Here's the AsyncStatus, AsyncHeaders messages:
```Elixir
%HTTPoison.AsyncStatus{code: 200, id: #Reference<0.0.0.2394>}
```

```Elixir
%HTTPoison.AsyncHeaders{headers: [{"Date", "Mon, 20 Jul 2015 16:25:45 GMT"}, {"Server", "Apache"}, {"Set-Cookie", "symfony=[...snip...] path=/; HttpOnly"}, {"Expires", "Thu, 19 Nov 1981 08:52:00 GMT"}, {"Cache-Control", "no-store, no-cache, must-revalidate, post-check=0, pre-check=0"}, {"Pragma", "no-cache"}, {"Vary", "Accept-Encoding,User-Agent"}, {"P3P", "CP=\"NOI CURa OUR NOR UNI\""}, {"Connection", "close"}, {"Content-Type", "application/rss+xml; charset=UTF-8"}], id: #Reference<0.0.0.2394>}
```

So it appears to be the same issue, only worse, because this server isn't even setting a content-length or transfer-encoding header on a `200 OK` response.

**Comment by DavsX** [comment] 2015-07-20 17:19
@jordan0day thank for the infinitely better-than-mine bug description :)

**Comment by edgurgel** [comment] 2015-07-21 10:13
Thanks! This is enough to reproduce the error. :+1:

**Comment by edgurgel** [comment] 2015-07-22 09:01
Good news. This was fixed with hackney 1.2.0. A simple `mix deps.update hackney` should do the job. I will set hackney to "~> 1.2" so nobody will have these problems.

Using hackney 1.2.0:

Running the 1 line "server"
```
{ echo -ne "HTTP/1.0 200 OK\r\n\r\n"; echo "BODY"; } | nc -l localhost 8080
```

```iex
iex(3)> HTTPoison.get!("http://localhost:8080", [], [stream_to: self])
%HTTPoison.AsyncResponse{id: #Reference<0.0.4.251>}
iex(4)> flush
%HTTPoison.AsyncStatus{code: 200, id: #Reference<0.0.4.251>}
%HTTPoison.AsyncHeaders{headers: [], id: #Reference<0.0.4.251>}
%HTTPoison.AsyncChunk{chunk: "BODY\n", id: #Reference<0.0.4.251>}
%HTTPoison.AsyncChunk{chunk: "", id: #Reference<0.0.4.251>}
%HTTPoison.AsyncEnd{id: #Reference<0.0.4.251>}
:ok
```

**Comment by DavsX** [comment] 2015-07-22 09:04
Good to hear! I'll try it myself, when I'll have the time.

**Closed** 2015-09-12 01:14 UTC

**Comment by DavsX** [comment] 2015-09-16 05:41
I confirm, that it is working :ok

**Comment by edgurgel** [comment] 2015-09-16 05:47
Awesome! Thanks! :+1:
