### ISSUE TITLE
(CaseClauseError) no case clause matching: [] with HTTPoison.get/1

### ISSUE THREAD

**Issue by uberbrodt** [edgurgel/httpoison#328] opened 2018-04-27 01:28 UTC
Here's an iex sample with Hackney tracing on. Using latest Hackney 1.12 and HTTPoison 1.1.0, and Elixir 1.6.4

```
iex(12)> HTTPoison.get "http://www.google.com"
[hackney trace 80 <0.376.0> 2018:04:27 00:24:27 492] request
   Content: [{module,hackney},
             {line,294},
             {method,get},
             {url,{hackney_url,hackney_tcp,http,<<"www.google.com">>,<<"/">>,
                               <<"/">>,<<>>,<<>>,"www.google.com",80,<<>>,
                               <<>>}},
             {headers,[]},
             {body,<<>>},
             {options,[{proxy,<<>>}]}]
[hackney trace 60 <0.376.0> 2018:04:27 00:24:27 492] HTTP proxy request
   Content: [{module,hackney},{line,603},{url,<<>>}]
** (CaseClauseError) no case clause matching: []
    (hackney) /home/cbrodt/Projects/traitify/gambit/deps/hackney/src/hackney_url.erl:192: :hackney_url.parse_netloc/2
    (hackney) /home/cbrodt/Projects/traitify/gambit/deps/hackney/src/hackney.erl:604: :hackney.maybe_proxy/4
    (hackney) /home/cbrodt/Projects/traitify/gambit/deps/hackney/src/hackney.erl:316: :hackney.request/5
    (httpoison) lib/httpoison/base.ex:469: HTTPoison.Base.request/9
```
0.13 works for me, however.

**Comment by chingan-tsc** [comment] 2018-08-02 10:44
Hi @uberbrodt, have you found a fix for this yet as I am also suffering from the same issue.

**Comment by edgurgel** [comment] 2018-08-02 20:01
my suspicion is that our code to auto-detect proxy configuration is not ignoring when it's an empty ENV VAR. Can someone check your ENV variables using `System.get_env` and look for `HTTP_PROXY` or `HTTPS_PROXY` ?

**Comment by uberbrodt** [comment] 2018-08-03 13:32
If I recall correctly I ended up downgrading to 0.13. I'll take a look later today

**Closed** 2018-08-26 04:38 UTC

**Comment by revdan** [comment] 2018-10-12 17:41
Hi there! Sorry to bump this, but I came across this error today, and the issue described here turned out to be a red herring for me.

In short, supplying a relative protocol URL also causes this error. 

```
iex(1)> HTTPoison.get "//google.com"
** (CaseClauseError) no case clause matching: []
```

I fixed it myself just by supplying a protocol, but I'm not sure if it's something you'd want to handle in HTTPoison too.

Many thanks,
Dan

**Comment by gabrielgrover** [comment] 2020-07-24 21:33
:httpoison, "~> 1.6"
elixir: "~> 1.9"

I am getting this same error what using HTTPoison.get!

Here is my code 

```
defmodule UserService.UserApi do 
  use HTTPoison.Base

  alias __MODULE__

  @base_endpoint "*"

  def process_request_url(endpoint), do:
    @base_endpoint <> endpoint  

  def process_response_body(body) do 
    body
    |> Poison.decode!
  end

  def register_user(email, password) do 
    headers = [{"Content-Type", "application/json"}]

    with body <- Poison.encode!(%{email: email, password: password}),
         %HTTPoison.Response{body: resp_body} = resp <- 
           ThriveApi.post!("/account/register", body, headers),
         registered_cookie = get_registered_cookie(resp)
    do
      reply(resp_body, %{email: email, registered_cookie: registered_cookie})
    else
      %HTTPoison.Error{reason: reason} -> {:error, reason}

      err -> {:error, err}
    end
  end

  def activate_membership("normal", registered_cookie), do:
    do_activate_membership("normal", registered_cookie)

  def activate_membership("d2t", registered_cookie), do:
    do_activate_membership("d2t", registered_cookie)
  
  def activate_membership(_, _), do:
    {:error, "invalid_member_type"}
  
  def add_address(address, registered_cookie) do
    headers = [{"Content-Type", "application/json"}, {"Cookie", registered_cookie}]

    with req_body <- Poison.encode!(address),
         %HTTPoison.Response{body: resp_body} <- 
           ThriveApi.post!("/account/address", req_body, headers)
    do
      reply(resp_body)
    else
      %HTTPoison.Error{reason: reason} -> {:error, reason}

      err -> {:error, err}
    end
  end

  def add_credit_card(registered_cookie) do 
    headers = [{"Content-Type", "application/json"}, {"Cookie", registered_cookie}]
    
    with req_body <- Poison.encode!(%{payment_method_nonce: "fake-valid-nonce"}),
         %HTTPoison.Response{body: resp_body} <-
           ThriveApi.post!("/account/cc", req_body, headers)
    do
      reply(resp_body)
    end
  end

  def get_credit_cards(registered_cookie) do 
    headers = [{"Content-Type", "application/json"}, {"Cookie", registered_cookie}]
    
    case HTTPoison.get!("/account/cc", headers) do 
      %HTTPoison.Response{body: resp_body} ->
        cards = Map.fetch!(resp_body, "cards")
        reply(resp_body, cards)

      %HTTPoison.Error{reason: reason} -> 
        {:error, reason}
    end
  end

  def set_autoship_type("opt_in", registered_cookie), do: 
    do_set_autoship_type("opt_in", registered_cookie)

  def set_autoship_type("opt_out", registered_cookie), do:
    do_set_autoship_type("opt_out", registered_cookie)

  def set_autoship_type(_, _), do: 
    {:error, "invalid_autoship_type"}

  def set_autoship_status("active", registered_cookie), do:
    do_set_autoship_status("active", registered_cookie)
    
  def set_autoship_status("inactive", registered_cookie), do:
    do_set_autoship_status("inactive", registered_cookie)
   
  def set_autoship_status("canceled", registered_cookie), do:
    do_set_autoship_status("canceled", registered_cookie)

  def set_autoship_status(_, _), do:
    {:error, "invalid_autoship_status"}

  
  defp do_set_autoship_status(status, registered_cookie) do 
    headers = [{"Content-Type", "application/json"}, {"Cookie", registered_cookie}]
    
    case ThriveApi.put!("/account?autoship_status=#{status}", "", headers, []) do
      %HTTPoison.Response{body: resp_body} -> 
        reply(resp_body)

      %HTTPoison.Error{reason: reason} -> {:error, reason}
    end
  end
    
  defp do_set_autoship_type(type, registered_cookie) do
    headers = [{"Content-Type", "application/json"}, {"Cookie", registered_cookie}]
    
    case ThriveApi.put!("/account?autoship_type=#{type}", "", headers, []) do
      %HTTPoison.Response{body: resp_body} -> 
        reply(resp_body)

      %HTTPoison.Error{reason: reason} -> {:error, reason}
    end
  end

  defp do_activate_membership(type, registered_cookie) do
    headers = [{"Content-Type", "application/json"}, {"Cookie", registered_cookie}]

    qs = if (type == "d2t"), do: "?type=D2T", else: ""
    
    case ThriveApi.post!("/account/membership/activate#{qs}", "", headers) do
      %HTTPoison.Response{body: resp_body} -> 
        reply(resp_body)

      %HTTPoison.Error{reason: reason} -> {:error, reason}
    end
  end

  defp get_registered_cookie(resp) do
    Enum.reduce(resp.headers, "", fn {header, value}, result ->
      case header do 
        "Set-Cookie" -> 
          cookie = String.replace(value, "secure", "")
                   |> String.trim()

          result <> cookie

        _otherwise -> result
      end
    end)
  end

  defp reply(%{"code" => 200}), do: :ok

  defp reply(body), do:
    {:error, Map.fetch!(body, "errors")}

  defp reply(%{"code" => 200}, resp), do: {:ok, resp}

  defp reply(%{"errors" => errors}, _), do:
    {:error, errors}

end
```

**Comment by AkshayVats** [comment] 2020-07-24 22:12
I am also getting the same error while trying to spin up Mozilla hubs on cloud.

`A 2020-07-22T09:51:30Z     (hackney 1.15.2) /app/deps/hackney/src/hackney_url.erl:224: :hackney_url.parse_netloc/2
A 2020-07-22T09:51:30Z     (hackney 1.15.2) /app/deps/hackney/src/hackney.erl:349: :hackney.request/5
A 2020-07-22T09:51:30Z     (httpoison 1.6.2) lib/httpoison/base.ex:796: HTTPoison.Base.request/6
A 2020-07-22T09:51:30Z     (httpoison 1.6.2) lib/httpoison.ex:128: HTTPoison.request!/5
A 2020-07-22T09:51:30Z     (ret 1.0.0) lib/ret/habitat.ex:13: Ret.Habitat.get_service_members/1
A 2020-07-22T09:51:30Z     (ret 1.0.0) lib/ret/peerage_provider.ex:5: Ret.PeerageProvider.poll/0
A 2020-07-22T09:51:30Z     (peerage 1.0.3) lib/peerage/server.ex:41: Peerage.Server.discover/0
A 2020-07-22T09:51:30Z     (peerage 1.0.3) lib/peerage/server.ex:29: Peerage.Server.handle_info/2
`
The error is caused by:
`%{status_code: 200, body: census_body} = HTTPoison.get!(census_url)`
where census_url is http://127.0.0.1: 9631

It would be nice if the error was more descriptive.

**Comment by albirrkarim** [comment] 2022-02-21 01:38
> census_body

im too

**Comment by Legendree** [comment] 2022-07-26 08:19
This issue still happens.

**Comment by lord-cosmos** [comment] 2024-05-19 20:56
yes, it happens for me too
