### ISSUE TITLE
Ensure headers passed to Hackney as case-insensitive?

### ISSUE THREAD

**Issue by tjsousa** [edgurgel/httpoison#100] opened 2015-11-23 22:18 UTC
I've run into an issue where I'm passing headers (including a `host` header) coming from a Plug's connection into `HTTPoison`, which default to lower-case, thus causing `:hackney` to override the `Host` header [(because it matches a capitalized one)](https://github.com/benoitc/hackney/blob/master/src/hackney.erl#L556-L560).

The referred use-case is for an app acting as a reverse-proxy where transparently passing headers, specially the `Host` header is very important.

[A workaround have been suggested](https://github.com/benoitc/hackney/issues/114#issuecomment-158752139), which I feel would be best implemented at the `httpoison` lib level to avoid this issue for other users as well.

What do you guys think?

**Comment by edgurgel** [comment] 2015-11-24 09:18
Hm.. I would open an issue to fix hackney so it looks for `Host` without a specific case, which seems to be the perfect solution. Would it fix the problem? 

cc/ @benoitc

**Comment by tjsousa** [comment] 2015-11-25 01:49
Yup, indeed. It seems like this existing issue could make it possible:
https://github.com/benoitc/hackney/issues/114

Thanks @edgurgel !

**Comment by gosseti** [comment] 2017-02-15 15:18
@tjsousa Just stumbled across this issue. I’m getting the error:

```
[error] proxy error: "HTTP/1.1 400 Bad Request\r\nContent-Type: text/plain\r\nConnection: close\r\n\r\n400 Bad Request: missing required Host header"
```

It’s related to the same one you’ve experienced above. Is there some way to explicitly pass the `Host` header to `HTTPoison` so that it doesn’t get overwritten/downcased by `hackney`? How did you solve this in the end?

I also put a StackOverflow question up here for it: http://stackoverflow.com/questions/42210304/elixir-httpoison-no-case-clause-matching-false-error

**Comment by suprafly** [comment] 2017-05-12 20:02
Still seeing this issue.

**Comment by benoitc** [comment] 2018-05-12 04:44
@tcitworld it has been fixed in hackney. Do you still reproduce the issue?

**Comment by tcitworld** [comment] 2018-05-12 07:43
You mean by using the hackney_headers module instead ?

**Comment by facundoolano** [comment] 2018-06-14 12:17
Still seeing this issue (case sensitive headers) in HTTPoison. And, to be honest, having to resort to hackney_headers kind of defeats the purpose of using an Elixir wrapper library.

**Comment by benoitc** [comment] 2018-06-14 14:01
Host header is passed once.

@facundoolano do yhave any example?

**Comment by facundoolano** [comment] 2018-06-14 14:44
@benoitc I guess my issue is more related to the title than the description. My main problem is that there's no case insensitive way to access response headers, so I need to know how the server sends them to fetch them, or manuallt downcase all the keys first.

**Comment by edgurgel** [comment] 2021-10-01 22:49
Closing due to inactivity. Happy to accept a PR to get a header from HTTPoison's module

**Closed by edgurgel** 2021-10-01 22:49 UTC
